sulu_security:
    type: rest
    resource: "@SuluSecurityBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_security.template.role.list:
     path: /template/role/list
     defaults:
         _controller: SuluSecurityBundle:Template:rolelist