sulu_security:
    type: rest
    resource: "@SuluSecurityBundle/Resources/config/routing_api.yml"
    prefix: /api


sulu_security.template.role.form:
     path: /template/role/form
     defaults:
         _controller: SuluSecurityBundle:Template:roleform

sulu_security.template.permission.form:
     path: /template/permission/form
     defaults:
         _controller: SuluSecurityBundle:Template:permissionform
