sulu_security:
    type: rest
    resource: "@SuluSecurityBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_security.template.role.form:
     path: /template/role/form
     defaults:
         _controller: SuluSecurityBundle:Template:roleForm