parameters:
    sulu_security.admin.class: Sulu\Bundle\SecurityBundle\Admin\SuluSecurityAdmin
    sulu_security.mask_converter.class: Sulu\Bundle\SecurityBundle\Permission\MaskConverter
    sulu_security.salt_generator.class: Sulu\Bundle\SecurityBundle\Permission\SaltGenerator
    sulu_security.admin.content_navigation.class: Sulu\Bundle\SecurityBundle\Admin\SuluSecurityContentNavigation

services:
    sulu_security.admin:
        class: %sulu_security.admin.class%
        tags:
        - { name: sulu.admin }

    sulu_security.mask_converter:
        class: %sulu_security.mask_converter.class%

    sulu_security.salt_generator:
        class: %sulu_security.salt_generator.class%

    sulu_security.content_navigation:
      class: %sulu_security.admin.content_navigation.class%
      tags:
      - { name: sulu.contact.admin.content_navigation }