parameters:
    permissions:
        view: 64
        add: 32
        edit: 16
        delete: 8
        archive: 4
        live: 2
        security: 1

    sulu_security.admin.class: Sulu\Bundle\SecurityBundle\Admin\SuluSecurityAdmin
    sulu_security.mask_converter.class: Sulu\Bundle\SecurityBundle\Permission\MaskConverter
    sulu_security.salt_generator.class: Sulu\Bundle\SecurityBundle\Permission\SaltGenerator
    sulu_security.admin.content_navigation.class: Sulu\Bundle\SecurityBundle\Admin\SuluSecurityContentNavigation
    sulu_security.admin.roles_navigation.class: Sulu\Bundle\SecurityBundle\Admin\SuluSecurityRolesContentNavigation
    sulu_security.permission_voter.class: Sulu\Bundle\SecurityBundle\Permission\PermissionVoter
    sulu_security.services.user_data_handler.class: Sulu\Bundle\SecurityBundle\Services\UserDataHandler
    sulu_user.class: Sulu\Bundle\SecurityBundle\Services\UserService

services:
    sulu_security.admin:
        class: %sulu_security.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }

    sulu_security.mask_converter:
        class: %sulu_security.mask_converter.class%
        arguments: [%permissions%]

    sulu_security.salt_generator:
        class: %sulu_security.salt_generator.class%

    sulu_security.content_navigation:
      class: %sulu_security.admin.content_navigation.class%
      tags:
      - { name: sulu.contact.admin.content_navigation }

    sulu_security.admin.roles_navigation:
      class: %sulu_security.admin.roles_navigation.class%

    user.services.user_data:
      class: %sulu_security.services.user_data_handler.class%
      arguments: [@security.context, @router]

    sulu_security.permission_voter:
        class: %sulu_security.permission_voter.class%
        arguments: [%permissions%]
        public: false
        tags:
            - { name: security.voter }

    sulu_security.sulu_manager:
        class: %sulu_user.class%
        arguments: [@doctrine]
