sulu_contact.contacts:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\ContactController

sulu_contact.accounts:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\AccountController
