sulu_contact.contacts:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\ContactController

sulu_contact.accounts:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\AccountController

sulu_contact.accountcategory:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\AccountCategoryController

sulu_contact.termsofpayment:
    type: rest
    resource: Sulu\Bundle\ContactBundle\Controller\TermsOfPaymentController
