parameters:
    sulu_contact.admin.class: Sulu\Bundle\ContactBundle\Admin\SuluContactAdmin
    sulu_contact.admin.content_navigation.class: Sulu\Bundle\ContactBundle\Admin\SuluContactContentNavigation
    sulu_contact.js_config.class: Sulu\Bundle\ContactBundle\Admin\SuluContactJsConfig

services:
    sulu_contact.admin:
        class: %sulu_contact.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }
    sulu_contact.admin.content_navigation:
        class: %sulu_contact.admin.content_navigation.class%

    sulu_contact.js_config:
        class: %sulu_contact.js_config.class%
        arguments:
          - 'contact-bundle'
          - type : 'basic'
            test : bla
        tags:
        - { name: sulu.js_config }
