sulu_admin:
    path:  /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'SuluAdminBundle:Admin:index.html.dist.twig'

sulu_admin.navigation:
    type: rest
    resource: Sulu\Bundle\AdminBundle\Controller\NavigationsController

sulu_admin.routes:
    path: /routes
    defaults:
        _controller: SuluAdminBundle:Admin:routes