parameters:
    sulu_admin.admin_pool.class: Sulu\Bundle\AdminBundle\Admin\AdminPool
    sulu_admin.name: %sulu_admin_name%

services:
    sulu_admin.admin_pool:
        class: %sulu_admin.admin_pool.class%
