parameters:
    sulu_tag.admin.class: Sulu\Bundle\TagBundle\Admin\SuluTagAdmin
    sulu_tag.tag_manager.class: Sulu\Bundle\TagBundle\Tag\TagManager
    sulu_tag.tag_repository.class: Sulu\Bundle\TagBundle\Entity\TagRepository
    sulu.content.type.tag_list.class: Sulu\Bundle\TagBundle\Content\Types\TagList

services:
    sulu_tag.admin:
        class: %sulu_tag.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
            - { name: sulu.admin }

    sulu_tag.tag_repository:
        class: %sulu_tag.tag_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["SuluTagBundle:Tag"]

    sulu_tag.tag_manager:
        class: %sulu_tag.tag_manager.class%
        arguments: ["@sulu_tag.tag_repository", "@doctrine.orm.entity_manager", "@event_dispatcher", "@security.context"]

    # Content types
    sulu.content.type.tag_list:
        class: %sulu.content.type.tag_list.class%
        arguments: ["@sulu_tag.tag_manager", %sulu.content.type.tag_list.template%]
