parameters:
    sulu.test_user_provider.class: Sulu\Bundle\TestBundle\Testing\TestUserProvider
    sulu.test_voter.class: Sulu\Bundle\TestBundle\Testing\TestVoter

services:
    test_user_provider:
        class: "%sulu.test_user_provider.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    test_voter:
        class: "%sulu.test_voter.class%"
        public: false
        tags:
            - { name: security.voter }
