parameters:
    sulu_website.admin.class: Sulu\Bundle\WebsiteBundle\Admin\SuluWebsiteAdmin
    sulu_website.navigation_mapper.class: Sulu\Bundle\WebsiteBundle\Navigation\NavigationMapper

services:
    sulu_website.admin:
        class: %sulu_website.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }

    sulu_website.navigation_mapper:
        class: %sulu_website.navigation_mapper.class%
        arguments: ["@sulu.content.mapper"]
