Sulu\Bundle\ContactBundle\Entity\Account:
    type: entity
    table: co_accounts
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        lft:
            type: integer
        rgt:
            type: integer
        depth:
            type: integer
        name:
            type: string
            length: '60'
        created:
            type: datetime
        changed:
            type: datetime
    oneToMany:
        contacts:
            targetEntity: Contact
            mappedBy: account
    manyToOne:
        parent:
            targetEntity: Account
            joinColumn:
                name: idAccountsParent
                referencedColumnName: id
        creator:
            targetEntity: Contact
            joinColumn:
                name: idContactsCreator
                referencedColumnName: id
                nullable: false
        changer:
            targetEntity: Contact
            joinColumn:
                name: idContactsChanger
                referencedColumnName: id
                nullable: false
    manyToMany:
        phones:
            targetEntity: Phone
            inversedBy: accounts
            joinTable:
                name: co_account_phones
                joinColumns:
                    idAccounts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idPhones:
                        referencedColumnName: id
        emails:
            targetEntity: Email
            inversedBy: accounts
            joinTable:
                name: co_account_emails
                joinColumns:
                    idAccounts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idEmails:
                        referencedColumnName: id
        notes:
            targetEntity: Note
            inversedBy: accounts
            joinTable:
                name: co_account_notes
                joinColumns:
                    idAccounts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idNotes:
                        referencedColumnName: id
        addresses:
            targetEntity: Address
            inversedBy: accounts
            joinTable:
                name: co_account_addresses
                joinColumns:
                    idAccounts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idAddresses:
                        referencedColumnName: id
        urls:
            targetEntity: Url
            inversedBy: accounts
            joinTable:
                name: co_account_urls
                joinColumns:
                    idAccounts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idUrls:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
