Sulu\Bundle\ContactBundle\Entity\Activity:
    type: entity
    table: co_activities
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
        due:
            type: datetime
            nullable: tru
        priority:
            type: integer
            nullable: true
        reminder:
            type: datetime
            nullable: true
        notification:
            type: boolean
        created:
            type: datetime
        changed:
            type: datetime
    manyToOne:
        contact:
            targetEntity: Contact
            inversedBy: activities
            joinColumn:
                name: idContacts
                referencedColumnName: id
                nullable: false
        activityStatus:
            targetEntity: ActivityStatus
            inversedBy: activities
            joinColumn:
                name: idActivityStatuses
                referencedColumnName: id
                nullable: false
        creator:
            targetEntity: Contact
            joinColumn:
                name: idContactsCreator
                referencedColumnName: id
                nullable: true
                onDelete: "set null"
        changer:
            targetEntity: Contact
            joinColumn:
                name: idContactsChanger
                referencedColumnName: id
                nullable: true
                onDelete: "set null"
    lifecycleCallbacks: {  }
