Sulu\Bundle\ContactBundle\Entity\ActivityStatus:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
    lifecycleCallbacks: {  }
