Sulu\Bundle\ContactBundle\Entity\Address:
    type: entity
    table: co_addresses
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        street:
            type: string
            length: '60'
        number:
            type: string
            length: '60'
        addition:
            type: string
            length: '60'
            nullable: true
        zip:
            type: string
            length: '60'
        city:
            type: string
            length: '60'
        state:
            type: string
            length: '60'
    manyToOne:
        addressType:
            targetEntity: AddressType
            inversedBy: addresses
            joinColumn:
                name: idAdressTypes
                referencedColumnName: id
                nullable: false
        country:
            targetEntity: Country
            inversedBy: addresses
            joinColumn:
                name: idCountries
                referencedColumnName: id
                nullable: false
    manyToMany:
        accounts:
            targetEntity: Account
            mappedBy: addresses
        contacts:
            targetEntity: Contact
            mappedBy: addresses
    lifecycleCallbacks: {  }
