Sulu\Bundle\ContactBundle\Entity\Contact:
    type: entity
    table: co_contacts
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fname:
            type: string
            length: '60'
        lname:
            type: string
            length: '60'
        title:
            type: string
            length: '60'
            nullable: true
        position:
            type: string
            length: '60'
            nullable: true
        localeSystem:
            type: string
            length: '2'
        username:
            type: string
            length: '60'
            nullable: true
        password:
            type: string
            length: '60'
            nullable: true
        created:
            type: datetime
        changed:
            type: datetime
    oneToMany:
        locales:
            targetEntity: ContactLocale
            mappedBy: contact
        activities:
            targetEntity: Activity
            mappedBy: contact
    manyToOne:
        account:
            targetEntity: Account
            inversedBy: contacts
            joinColumn:
                name: idAccounts
                referencedColumnName: id
        creator:
            targetEntity: Contact
            joinColumn:
                name: idContactsCreator
                referencedColumnName: id
                nullable: false
        changer:
            targetEntity: Contact
            joinColumn:
                name: idContactsChanger
                referencedColumnName: id
                nullable: false
    manyToMany:
        phones:
            targetEntity: Phone
            inversedBy: contacts
            joinTable:
                name: co_contact_phones
                joinColumns:
                    idContacts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idPhones:
                        referencedColumnName: id
        addresses:
            targetEntity: Address
            inversedBy: contacts
            joinTable:
                name: co_contact_addresses
                joinColumns:
                    idContacts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idAddresses:
                        referencedColumnName: id
        notes:
            targetEntity: Note
            inversedBy: contacts
            joinTable:
                name: co_contact_notes
                joinColumns:
                    idContacts:
                        referencedColumnName: id
                inverseJoinColumns:
                    idNotes:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
