Sulu\Bundle\ContactBundle\Entity\Country:
    type: entity
    table: co_countries
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
        code:
            type: string
            length: '60'
    oneToMany:
        addresses:
            targetEntity: Address
            mappedBy: country
    lifecycleCallbacks: {  }
