Sulu\Bundle\ContactBundle\Entity\EmailType:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
    oneToMany:
        emails:
            targetEntity: Email
            mappedBy: emailType
    lifecycleCallbacks: {  }
