Sulu\Bundle\ContactBundle\Entity\Email:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        email:
            type: string
            length: '60'
    manyToOne:
        emailType:
            targetEntity: EmailType
            inversedBy: emails
            joinColumn:
                name: idEmailTypes
                referencedColumnName: id
    manyToMany:
        accounts:
            targetEntity: Account
            mappedBy: emails
    lifecycleCallbacks: {  }
