Sulu\Bundle\ContactBundle\Entity\PhoneType:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
    oneToMany:
        phones:
            targetEntity: Phone
            mappedBy: phoneType
    lifecycleCallbacks: {  }
