Sulu\Bundle\ContactBundle\Entity\Url:
    type: entity
    table: co_urls
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        url:
            type: string
            length: 255
    manyToOne:
        urlType:
            targetEntity: UrlType
            inversedBy: urls
            joinColumn:
                name: idUrlTypes
                referencedColumnName: id
                nullable: false
    manyToMany:
        accounts:
            targetEntity: Account
            mappedBy: urls
    lifecycleCallbacks: {  }
