Sulu\Bundle\ContactBundle\Entity\UrlType:
    type: entity
    table: co_url_types
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
    oneToMany:
        urls:
            targetEntity: Url
            mappedBy: urlType
    lifecycleCallbacks: {  }
