sulu_media.website.image.proxy:
    path: /uploads/media/{slug}
    defaults: { _controller: SuluMediaBundle:WebsiteMedia:getImage }
    requirements:
        slug: .*

sulu_media.website.media.download:
    path: /uploads/download/{id}/{slug}
    defaults: { _controller: SuluMediaBundle:WebsiteMedia:download }
    requirements:
        slug: .*
