sulu_content.content:
    type: rest
    resource: Sulu\Bundle\ContentBundle\Controller\NodeController

sulu_content.resource_locator:
    type: rest
    resource: Sulu\Bundle\ContentBundle\Controller\ResourcelocatorController
