sulu_content.rl:
    type: rest
    resource: Sulu\Bundle\ContentBundle\Controller\NodeResourcelocatorController

sulu_content.node:
    type: rest
    resource: Sulu\Bundle\ContentBundle\Controller\NodeController

