content_form:
    pattern: /template/form/{key}
    defaults: { _controller: SuluContentBundle:Template:content }

sulu_content.content_navigation:
    path: /navigation/content
    defaults: { _controller: SuluContentBundle:Navigation:content }
