sulu_content.content_form:
    pattern: /template/form/{key}.html
    defaults: { _controller: SuluContentBundle:Template:content }

sulu_content.content_navigation:
    path: /navigation/content
    defaults: { _controller: SuluContentBundle:Navigation:content }

sulu_content.content_list:
    pattern: /template/content/list.html
    defaults: { _controller: SuluContentBundle:Template:list }

sulu_content.content_column:
    pattern: /template/content/column.html
    defaults: { _controller: SuluContentBundle:Template:column }

sulu_content.resource_locator_get:
    pattern: /resourcelocator.json
    defaults: { _controller: SuluContentBundle:ResourceLocator:get }

sulu_content.preview.render:
    pattern: /preview/{contentUuid}.html
    methods: GET
    defaults: { _controller: SuluContentBundle:Preview:render }

sulu_content.preview.update:
    pattern: /preview/{contentUuid}
    methods: POST
    defaults: { _controller: SuluContentBundle:Preview:update }

sulu_content.preview.changes:
    pattern: /preview/{contentUuid}.json
    methods: GET
    defaults: { _controller: SuluContentBundle:Preview:changes }
