sulu_content.content_form:
    pattern: /template/form/{key}.html
    defaults: { _controller: SuluContentBundle:Template:content }

sulu_content.content_navigation:
    path: /navigation/content
    defaults: { _controller: SuluContentBundle:Navigation:content }

sulu_content.content_list:
    pattern: /template/content/list.html
    defaults: { _controller: SuluContentBundle:Template:list }
