parameters:
    sulu_content.admin.class: Sulu\Bundle\ContentBundle\Admin\SuluContentAdmin
    sulu_content.twig_extension.class: Sulu\Bundle\ContentBundle\Twig\ContentExtension
    sulu_content.admin.content_navigation.class: Sulu\Bundle\ContentBundle\Admin\SuluContentContentNavigation
    sulu_content.preview.message_component.class: Sulu\Bundle\ContentBundle\Preview\PreviewMessageComponent

services:
    sulu_content.admin:
        class: %sulu_content.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }
    sulu_content.admin.content_navigation:
        class: %sulu_content.admin.content_navigation.class%
    sulu_content.twig_extension:
        class: %sulu_content.twig_extension.class%
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            - { name: twig.extension }
    sulu_content.preview.message_component:
        class: %sulu_content.preview.message_component.class%
