parameters:
    sulu_content.admin.class: Sulu\Bundle\ContentBundle\Admin\SuluContentAdmin
    sulu_content.twig_extension.class: Sulu\Bundle\ContentBundle\Twig\ContentExtension
    sulu_content.admin.content_navigation.class: Sulu\Bundle\ContentBundle\Admin\SuluContentContentNavigation
    sulu_content.get_contact.class: Sulu\Bundle\ContentBundle\Controller\Repository\GetContactName
    sulu_content.node_repository.class: Sulu\Bundle\ContentBundle\Controller\Repository\NodeRepository

services:
    sulu_content.admin:
        class: %sulu_content.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }
    sulu_content.admin.content_navigation:
        class: %sulu_content.admin.content_navigation.class%
    sulu_content.twig_extension:
        class: %sulu_content.twig_extension.class%
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            - { name: twig.extension }
    sulu_content.get_contact:
        public: false
        class: %sulu_content.get_contact.class%
        arguments: [@doctrine]
    sulu_content.node_repository:
        class: %sulu_content.node_repository.class%
        arguments: [@sulu.content.mapper, @sulu_content.get_contact, @security.context]
